#!/bin/bash

# Exit if any command fails
set -e

# Generate .env file
echo "Generating .env file..."

ACCESS_KEY_ID=$(terraform output -raw s3_upload_aws_access_key_id)
SECRET_ACCESS_KEY=$(terraform output -raw s3_upload_aws_secret_access_key)
BUCKET_NAME=$(terraform output -raw bucket_name)
REGION=$(terraform output -raw region)
ALERT_EMAIL=$(terraform output -raw alert_email)

cat > ./camerahost/.env <<EOF
# Auto-generated by generate-env.sh
AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
BUCKET_NAME=${BUCKET_NAME}
REGION=${REGION}
ALERT_EMAIL=${ALERT_EMAIL}
EOF

echo ".env file created successfully in ./camerahost/.env"

