#!/bin/bash

# Exit if any command fails
set -e

# Generate .env file
echo "Generating .env file..."

ACCESS_KEY_ID=$(terraform output -raw s3_upload_aws_access_key_id)
SECRET_ACCESS_KEY=$(terraform output -raw s3_upload_aws_secret_access_key)

cat > .env <<EOF
# Auto-generated by generate-env.sh
AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
EOF

echo ".env file created successfully."

