#!/bin/bash

# Exit if any command fails
set -e

# Generate .env file
echo "Generating .env file..."

BUCKET_NAME=$(terraform output -raw bucket_name)
REGION=$(terraform output -raw region)
ALERT_EMAIL=$(terraform output -raw alert_email)

cat > ./camerahost/.env <<EOF
# Auto-generated by generate-env.sh
BUCKET_NAME=${BUCKET_NAME}
REGION=${REGION}
ALERT_EMAIL=${ALERT_EMAIL}
MAILGUN_API_KEY=
MAILGUN_DOMAIN=
EOF

echo ".env file created successfully in ./camerahost/.env"

